version = 1

[[annotations]]
path = ["apps/frontend/public/splatoon/maps/*.jpg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Nintendo"
SPDX-License-Identifier = "LicenseRef-Proprietary"

[[annotations]]
path = ["apps/frontend/public/cs2/**.png", "apps/frontend/public/cs2/**.jpg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Valve Corporation"
SPDX-License-Identifier = "LicenseRef-Proprietary"

[[annotations]]
path = ["apps/frontend/public/valorant/maps/*.jpg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Riot Games"
SPDX-License-Identifier = "LicenseRef-Proprietary"

[[annotations]]
path = ["apps/frontend/public/CSM*.svg", "apps/frontend/public/coin_*.webm"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 CyberSport Masters <git@csmpro.ru>"
SPDX-License-Identifier = "LicenseRef-CyberSportMasters"

[[annotations]]
path = [
    "apps/frontend/public/splatoon/modes/**.png",
    "apps/frontend/public/valorant/ct.jpg",
    "apps/frontend/public/valorant/t.jpg",
    "apps/frontend/public/valorant/ct_white.png",
    "apps/frontend/public/valorant/t_white.png",
    "apps/frontend/src/app/favicon.ico"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 CyberSport Masters <git@csmpro.ru>"
SPDX-License-Identifier = "CC-BY-SA-4.0"

[[annotations]]
path = [
    "**/.gitignore",
    ".npmrc",
    "yarn.lock",
    "**/package.json",
    "turbo.json",
    "apps/*/tsconfig.json",
    "apps/*/.eslintrc.json",
    "apps/frontend/components.json",
    "apps/backend/nodemon.json",
    ".forgejo/workflows/docker-images.yml",
    ".forgejo/workflows/codeql.yml"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024-2025 CyberSport Masters <git@csmpro.ru>"
SPDX-License-Identifier = "AGPL-3.0-only"

[[annotations]]
path = ["apps/frontend/src/app/fonts/Geist*.woff"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 The Geist Project Authors"
SPDX-License-Identifier = "OFL-1.1"
