name: "CD"

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-docker:
    name: Build and Push Docker Images
    runs-on: node

    steps:
      - name: Checkout Repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Install bun
        uses: https://github.com/oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2

      - name: Install Docker
        run: |
          apt update
          apt install -y docker.io

      - name: Log in to Forgejo Container Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        with:
          registry: git.in.csmpro.ru
          username: ${{ forge.repository_owner }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Build Backend Image
        run: |
          docker build \
            -f apps/backend/Dockerfile \
            -t git.in.csmpro.ru/${{ forge.repository_owner }}/csm-mapban/backend:latest .

      - name: Push Backend Image
        run: |
          docker push git.in.csmpro.ru/${{ forge.repository_owner }}/csm-mapban/backend:latest

      - name: Build Frontend Image
        run: |
          docker build \
            -f apps/frontend/Dockerfile \
            -t git.in.csmpro.ru/${{ forge.repository_owner }}/csm-mapban/frontend:latest .

      - name: Push Frontend Image
        run: |
          docker push git.in.csmpro.ru/${{ forge.repository_owner }}/csm-mapban/frontend:latest

      - name: Trigger Portainer webhook
        env:
          PORTAINER_WEBHOOK_URL: ${{ secrets.PORTAINER_WEBHOOK_URL }}
        run: curl -fsS -m 30 -X POST "$PORTAINER_WEBHOOK_URL"
