name: "REUSE Compliance Check"

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  reuse-lint:
    runs-on: node-bookworm

    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      
      - name: Run REUSE Compliance Check
        uses: https://github.com/fsfe/reuse-action@28cf8f33bc50f4c306f52e38fe3826717dea63dc # v1