name: "REUSE Compliance Check"

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  reuse-lint:
    runs-on: node-bookworm

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Run REUSE Compliance Check
        uses: https://github.com/fsfe/reuse-action@bb774aa972c2a89ff34781233d275075cbddf542 # v5
